on:
  - push
  - workflow_dispatch

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: test script
        run: |
          sudo systemctl stop autofs
          sudo cvmfs_ducc convert recipe.yaml --skip-podman --skip-thin-image
